services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:7
    container_name: redis_server
    restart: always
    ports:
      - "6380:6379" # host:container


  web:
    build: .
    container_name: fastapi-template
    restart: always
    depends_on:
      - db
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  postgres_data: